config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/about'
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<!-- Header -->
  <div id="header">
    <div class="container">

      <!-- Logo -->
        <div id="logo">
          <span class="pennant"><span class="icon fa-futbol-o"></span></span>
          <h1><a href="index.html">Basket</a></h1>
        </div>

      <!-- Nav -->
        <nav id="nav">
          <ul>
            <li class="active"><a href="<%= root_path %>">Home</a></li>
            <li><a href="<%= pages_about_path %>">About</a></li>
            <li><a href="apage.html">A Page</a></li>
            <li>
              <a href="#" class="icon fa-caret-down">Drop Down Menu</a>
              <ul>
                <li><a href="#">Example Menu</a></li>
                <li><a href="#">Example Menu</a></li>
                <li><a href="#">Example Menu</a></li>
                <li><a href="#">Example Menu</a></li>
                <li>
                  <a href="#">Example Submenu</a>
                  <ul>
                    <li><a href="#">Example Menu</a></li>
                    <li><a href="#">Example Menu</a></li>
                    <li><a href="#">Example Menu</a></li>
                    <li><a href="#">Example Menu</a></li>
                  </ul>
                </li>
              </ul>
            </li>
            <li><a href="contact.php">Contact Page</a></li>
          </ul>
        </nav>

    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ejemplo02</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page-wrapper">

<!-- Banner -->
  <div id="banner">
    <div class="container">						
      <div class="row">
        <div class="9u 12u(mobile)">
          <section>
            <a class="image full"><img src="<%= asset_path 'banner.jpg' %>" alt="" /></a>
          </section>
        </div>
        <div class="3u 12u(mobile)">
          <section>
            <div class="bannerbox">
              <h2>Headline</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem.</p>
            </div>
          </section>
        </div>							
      </div>
    </div>
  </div>

<!-- Featured -->
  <div id="featured">
    <section class="container">
      <header>
        <h2>Business Name</h2>
        <span class="byline">Your Business strapline goes here</span>
      </header>
    </section>
  </div>
  
<!-- Main -->
  <div id="main">
    <section class="container">
      <div class="row">
        <section class="3u 12u(mobile)">
          <a href="#" class="image full"><img src="<%= asset_path 'pic01.jpg' %>" alt="" /></a>
          <div class="box">
            <h3><a href="#">Service</a></h3>
          </div>
        </section>
        <section class="3u 12u(mobile)">
          <a href="#" class="image full"><img src="<%= asset_path 'pic02.jpg' %>" alt="" /></a>
          <div class="box">
            <h3><a href="#">Service</a></h3>
          </div>
        </section>
        <section class="3u 12u(mobile)">
          <a href="#" class="image full"><img src="<%= asset_path 'pic03.jpg' %>" alt="" /></a>
          <div class="box">
            <h3><a href="#">Service</a></h3>
          </div>
        </section>
        <section class="3u 12u(mobile)">
          <a href="#" class="image full"><img src="<%= asset_path 'pic04.jpg' %>" alt="" /></a>
          <div class="box">
            <h3><a href="#">Service</a></h3>
          </div>
        </section>							
      </div>					
      <h2>Welcome To Our New Website</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem, lacinia eu auctor eget, dapibus feugiat elit. Duis lectus justo, ultrices ac placerat non, sollicitudin at massa. Integer pulvinar ipsum a posuere consectetur. Aenean placerat, quam sed varius congue, felis lectus ullamcorper massa, nec posuere ante massa finibus tortor. Nulla facilisi. Maecenas porttitor felis et tempor vulputate. Fusce ligula ante, venenatis hendrerit semper at, posuere vel velit. Pellentesque commodo nulla vel nisi fringilla, id malesuada sapien dictum. Morbi eget lobortis nulla. Suspendisse id aliquet felis.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem, lacinia eu auctor eget, dapibus feugiat elit. Duis lectus justo, ultrices ac placerat non, sollicitudin at massa. Integer pulvinar ipsum a posuere consectetur. Aenean placerat, quam sed varius congue, felis lectus ullamcorper massa, nec posuere ante massa finibus tortor. Nulla facilisi. Maecenas porttitor felis et tempor vulputate. Fusce ligula ante, venenatis hendrerit semper at, posuere vel velit. Pellentesque commodo nulla vel nisi fringilla, id malesuada sapien dictum. Morbi eget lobortis nulla. Suspendisse id aliquet felis.</p>
    </section>
  </div>

<!-- Footer -->
  <div id="footer">
    <div class="container">
      <section>
        <div class="row">
          <div class="3u 12u(mobile)">
            <header>
              <h2>Heading</h2>
            </header>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem, lacinia eu auctor eget, dapibus feugiat elit. Duis lectus justo, ultrices ac placerat non, sollicitudin at massa.</p>
            <a href="#" class="button">More</a>
          </div>
          <div class="3u 12u(mobile)">
            <header>
              <h2>Heading</h2>
            </header>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem, lacinia eu auctor eget, dapibus feugiat elit. Duis lectus justo, ultrices ac placerat non, sollicitudin at massa.</p>
            <a href="#" class="button">More</a>								
          </div>
          <div class="3u 12u(mobile)">
            <header>
              <h2>Heading</h2>
            </header>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem, lacinia eu auctor eget, dapibus feugiat elit. Duis lectus justo, ultrices ac placerat non, sollicitudin at massa.</p>
            <a href="#" class="button">More</a>								
          </div>
          <div class="3u 12u(mobile)">
            <header>
              <h2>Heading</h2>
            </header>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem, lacinia eu auctor eget, dapibus feugiat elit. Duis lectus justo, ultrices ac placerat non, sollicitudin at massa.</p>
            <a href="#" class="button">More</a>								
          </div>								
        </div>								
      </section>

      <!-- Social -->
        <section>
          <ul class="icons">
            <li><a href="#" class="icon fa-twitter"><span>Twitter</span></a></li>
            <li><a href="#" class="icon fa-facebook"><span>Facebook</span></a></li>
            <li><a href="#" class="icon fa-google-plus"><span>Google+</span></a></li>
            <li><a href="#" class="icon fa-linkedin"><span>Linkedin</span></a></li>
            <li><a href="#" class="icon fa-pinterest"><span>Pinterest</span></a></li>
          </ul>
        </section>

      <!-- Copyright -->
        <div class="copyright">
          &copy; CSS3_Basket | <a href="http://www.css3templates.co.uk">a css3templates.co.uk design</a>								
        </div>

    </div>
  </div>

</div>

app/views/pages/index.html.erb
	<div id="page-wrapper">

  <!-- Banner -->
    <div id="banner">
      <div class="container">						
        <div class="row">
          <div class="9u 12u(mobile)">
            <section>
              <a class="image full"><img src="<%= asset_path 'banner.jpg' %>" alt="" /></a>
            </section>
          </div>
          <div class="3u 12u(mobile)">
            <section>
              <div class="bannerbox">
                <h2>Headline</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem.</p>
              </div>
            </section>
          </div>							
        </div>
      </div>
    </div>

  <!-- Featured -->
    <div id="featured">
      <section class="container">
        <header>
          <h2>Business Name</h2>
          <span class="byline">Your Business strapline goes here</span>
        </header>
      </section>
    </div>
    
  <!-- Main -->
    <div id="main">
      <section class="container">
        <div class="row">
          <section class="3u 12u(mobile)">
            <a href="#" class="image full"><img src="<%= asset_path 'pic01.jpg' %>" alt="" /></a>
            <div class="box">
              <h3><a href="#">Service</a></h3>
            </div>
          </section>
          <section class="3u 12u(mobile)">
            <a href="#" class="image full"><img src="<%= asset_path 'pic02.jpg' %>" alt="" /></a>
            <div class="box">
              <h3><a href="#">Service</a></h3>
            </div>
          </section>
          <section class="3u 12u(mobile)">
            <a href="#" class="image full"><img src="<%= asset_path 'pic03.jpg' %>" alt="" /></a>
            <div class="box">
              <h3><a href="#">Service</a></h3>
            </div>
          </section>
          <section class="3u 12u(mobile)">
            <a href="#" class="image full"><img src="<%= asset_path 'pic04.jpg' %>" alt="" /></a>
            <div class="box">
              <h3><a href="#">Service</a></h3>
            </div>
          </section>							
        </div>					
        <h2>Welcome To Our New Website</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem, lacinia eu auctor eget, dapibus feugiat elit. Duis lectus justo, ultrices ac placerat non, sollicitudin at massa. Integer pulvinar ipsum a posuere consectetur. Aenean placerat, quam sed varius congue, felis lectus ullamcorper massa, nec posuere ante massa finibus tortor. Nulla facilisi. Maecenas porttitor felis et tempor vulputate. Fusce ligula ante, venenatis hendrerit semper at, posuere vel velit. Pellentesque commodo nulla vel nisi fringilla, id malesuada sapien dictum. Morbi eget lobortis nulla. Suspendisse id aliquet felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem, lacinia eu auctor eget, dapibus feugiat elit. Duis lectus justo, ultrices ac placerat non, sollicitudin at massa. Integer pulvinar ipsum a posuere consectetur. Aenean placerat, quam sed varius congue, felis lectus ullamcorper massa, nec posuere ante massa finibus tortor. Nulla facilisi. Maecenas porttitor felis et tempor vulputate. Fusce ligula ante, venenatis hendrerit semper at, posuere vel velit. Pellentesque commodo nulla vel nisi fringilla, id malesuada sapien dictum. Morbi eget lobortis nulla. Suspendisse id aliquet felis.</p>
      </section>
    </div>

  <!-- Footer -->
    <div id="footer">
      <div class="container">
        <section>
          <div class="row">
            <div class="3u 12u(mobile)">
              <header>
                <h2>Heading</h2>
              </header>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem, lacinia eu auctor eget, dapibus feugiat elit. Duis lectus justo, ultrices ac placerat non, sollicitudin at massa.</p>
              <a href="#" class="button">More</a>
            </div>
            <div class="3u 12u(mobile)">
              <header>
                <h2>Heading</h2>
              </header>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem, lacinia eu auctor eget, dapibus feugiat elit. Duis lectus justo, ultrices ac placerat non, sollicitudin at massa.</p>
              <a href="#" class="button">More</a>								
            </div>
            <div class="3u 12u(mobile)">
              <header>
                <h2>Heading</h2>
              </header>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem, lacinia eu auctor eget, dapibus feugiat elit. Duis lectus justo, ultrices ac placerat non, sollicitudin at massa.</p>
              <a href="#" class="button">More</a>								
            </div>
            <div class="3u 12u(mobile)">
              <header>
                <h2>Heading</h2>
              </header>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet egestas eros. Sed venenatis est nunc, id convallis tellus venenatis non. Proin id nisi euismod, molestie nisl vel, accumsan sem. Integer felis sem, lacinia eu auctor eget, dapibus feugiat elit. Duis lectus justo, ultrices ac placerat non, sollicitudin at massa.</p>
              <a href="#" class="button">More</a>								
            </div>								
          </div>								
        </section>

        <!-- Social -->
          <section>
            <ul class="icons">
              <li><a href="#" class="icon fa-twitter"><span>Twitter</span></a></li>
              <li><a href="#" class="icon fa-facebook"><span>Facebook</span></a></li>
              <li><a href="#" class="icon fa-google-plus"><span>Google+</span></a></li>
              <li><a href="#" class="icon fa-linkedin"><span>Linkedin</span></a></li>
              <li><a href="#" class="icon fa-pinterest"><span>Pinterest</span></a></li>
            </ul>
          </section>

        <!-- Copyright -->
          <div class="copyright">
            &copy; CSS3_Basket | <a href="http://www.css3templates.co.uk">a css3templates.co.uk design</a>								
          </div>

      </div>
    </div>

</div>